# Site settings
title: Seiren's Dubbing Diary
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Seiren
user_description: 
  안녕하세요!
  저는 목원대학교 정보통신공학과 21학번 이유민입니다. <br>
  2002년 2월 1일에 태어났고, 혈액형은 A형, MBTI는 ENFP입니다! <br>
  웹 개발자를 꿈꾸며 열심히 달려가는 중입니다. <br>
  앞으로 더욱 발전하는 모습 보여드리겠습니다. <br>
  방문해주셔서 감사합니다. 좋은 하루 되세요! 


user_title: Thank you for visiting my website!
github_username:  bySeiren02


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
